### ISSUE TITLE
Translate Up & Going

### ISSUE THREAD

**Issue by huytd** [node-vietnam/You-Dont-Know-JS#3]
- [x] Mục lục
- [ ] Lời tựa (by Jenn Lukas)
- [ ] Mở đầu
- [ ] Chương 1: Giới thiệu về Lập trình
- [ ] Chương 2: Giới thiệu JavaScript
- [ ] Chương 3: Giới thiệu YDKJS
- [ ] Phụ lục A: Thank You's!

**Comment by hoasung01** [comment]
@huytd 
đang dịch Chương 1 nhé :)

**Comment by huytd** [comment]
Ợ, ok bác, vậy e move qua chương khác nhé 👍

**Comment by hoasung01** [comment]
ok cậu, plan là CN tuần sau mình xong chương 1 :)

**Comment by huytd** [comment]
👍  :(
